apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- namespace.yaml

images:
- name: 591446362507.dkr.ecr.eu-west-2.amazonaws.com/sre-sample-app
  newName: 591446362507.dkr.ecr.eu-west-2.amazonaws.com/sre-sample-app
  newTag: 89a7a8e32d8885b9e348e26c76e0a252b6828050
