apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: 591446362507.dkr.ecr.eu-west-2.amazonaws.com/sre-sample-app
  newName: 591446362507.dkr.ecr.eu-west-2.amazonaws.com/sre-sample-app
  newTag: 93431b74c82073715f1b257143b88cc1b6a3cda0
