name: Destroy Sample App

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Remove from EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region eu-west-2 \
            --name sre-portfolio-cluster

      - name: Remove from EKS
        run: |
          kubectl delete -f kubernetes/deployment.yaml --ignore-not-found
          kubectl delete -f kubernetes/service.yaml --ignore-not-found